# Generated by Django 5.1.6 on 2025-03-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='Email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='logindata',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
