# Generated by Django 5.1.6 on 2025-03-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0002_logindata_email_logindata_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('P_id', models.IntegerField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=255)),
                ('P_title', models.CharField(max_length=255)),
                ('P_Description', models.TextField()),
                ('P_img', models.ImageField(upload_to='product_images/')),
                ('P_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
