# Generated by Django 5.1.6 on 2025-03-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
