# Generated by Django 5.1.6 on 2025-03-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0004_alter_product_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='P_Quality',
            field=models.IntegerField(default=1),
        ),
    ]
