# Generated by Django 5.2 on 2025-04-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0005_product_p_quality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginData',
        ),
    ]
