# Generated by Django 5.2 on 2025-05-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0012_order_is_paid_order_paypal_payer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paypal_payer_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paypal_payment_id',
            new_name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('menu', models.CharField(choices=[('plants', 'Plants'), ('seeds', 'Seeds'), ('crop_nutrition', 'Crop Nutrition'), ('crop_protection', 'Crop Protection'), ('equipment', 'Agricultural Equipment')], max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='agrobuild.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='agrobuild.category'),
        ),
    ]
