# Generated by Django 5.2 on 2025-05-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0019_blog_alter_contactmessage_created_at_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='P_Quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='P_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
