# Generated by Django 5.2 on 2025-05-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0020_remove_product_p_quality_remove_product_p_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
