# Generated by Django 5.2 on 2025-05-08 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0022_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='monsoon_watering',
            field=models.CharField(choices=[('daily', 'Daily'), ('twice', 'Twice a day'), ('every_two_days', 'Every two days'), ('weekly', 'Weekly')], default='every_two_days', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='summer_watering',
            field=models.CharField(choices=[('daily', 'Daily'), ('twice', 'Twice a day'), ('every_two_days', 'Every two days'), ('weekly', 'Weekly')], default='daily', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='winter_watering',
            field=models.CharField(choices=[('daily', 'Daily'), ('twice', 'Twice a day'), ('every_two_days', 'Every two days'), ('weekly', 'Weekly')], default='twice', max_length=50),
        ),
        migrations.CreateModel(
            name='PlantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_time', models.TimeField(blank=True, null=True)),
                ('evening_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrobuild.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
