# Generated by Django 5.2 on 2025-05-09 07:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0023_product_monsoon_watering_product_summer_watering_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plantnotification',
            name='allow_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plantnotification',
            name='evening_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='plantnotification',
            name='morning_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='product',
            name='monsoon_watering',
            field=models.CharField(choices=[('daily', 'Daily'), ('twice', 'Twice a day'), ('every_two_days', 'Every two days'), ('weekly', 'Weekly')], default='every_two_days', max_length=50, verbose_name='Monsoon (Jul-Oct) Watering'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summer_watering',
            field=models.CharField(choices=[('daily', 'Daily'), ('twice', 'Twice a day'), ('every_two_days', 'Every two days'), ('weekly', 'Weekly')], default='daily', max_length=50, verbose_name='Summer (Mar-Jun) Watering'),
        ),
        migrations.AlterField(
            model_name='product',
            name='winter_watering',
            field=models.CharField(choices=[('daily', 'Daily'), ('twice', 'Twice a day'), ('every_two_days', 'Every two days'), ('weekly', 'Weekly')], default='twice', max_length=50, verbose_name='Winter (Nov-Feb) Watering'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('keys', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
