# Generated by Django 5.2 on 2025-05-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0025_alter_plantnotification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
