# Generated by Django 5.2 on 2025-05-09 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0026_category_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantnotification',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantnotification',
            name='morning_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
