# Generated by Django 5.2.1 on 2025-05-12 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0029_notificationhistory_is_read_wateringreminder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='user',
        ),
        migrations.RenameField(
            model_name='wateringreminder',
            old_name='allow_push',
            new_name='allow_gmail',
        ),
        migrations.RemoveField(
            model_name='wateringreminder',
            name='last_evening_sent',
        ),
        migrations.RemoveField(
            model_name='wateringreminder',
            name='last_morning_sent',
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='allow_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrobuild.category'),
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PlantNotification',
        ),
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
