# Generated by Django 5.2.1 on 2025-05-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0030_alter_pushsubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('paid', 'Paid')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_transaction_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
