# Generated by Django 5.2.3 on 2025-06-29 12:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0034_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_Description',
            field=models.TextField(help_text='Detailed description of the product.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='P_img',
            field=models.ImageField(default='', help_text='Upload a clear product image.', upload_to='image/img', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='P_name',
            field=models.CharField(help_text='Enter the product name.', max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='P_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set the product price.', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=5, help_text='Available stock for the product.'),
        ),
    ]
