# Generated by Django 5.2.1 on 2025-07-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrobuild', '0036_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
    ]
