"""
Django settings for agro project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
 
from pathlib import Path
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-f-if+h2&0p+8f9c91obcs6&05d1mc&r#e01azh9dj^3)34e_=i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [ # components
    'jazzmin',  # For better admin interface
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agrobuild',
    'pytz',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'agrobuild/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'agrobuild.context_processors.cart_data',
                'agrobuild.context_processors.cart_items_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'agro.wsgi.application'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
NOTIFICATION_SOUND = os.path.join(BASE_DIR, 'static/sounds/notification.mp3')

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    os.path.join(BASE_DIR, 'static'), 
    os.path.join(BASE_DIR, 'agrobuild/static'),

]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
RAZORPAY_KEY_ID = 'your_razorpay_key_id'
RAZORPAY_KEY_SECRET = 'your_razorpay_key_secret'

# Set your timezone (e.g., for India)
TIME_ZONE = 'Asia/Kolkata'

# Use timezone-aware datetimes
USE_TZ = True

# Gmail SMTP settings for sending watering reminders
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'shopmulti9859@gmail.com'         
EMAIL_HOST_PASSWORD = 'webv rzla nzog avom'       
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

JAZZMIN_SETTINGS = {

    # General Settings
    "site_title": "Agro Build Admin",
    "site_header": "Agro Build",
    "site_brand": "🌱 Agro Build",
    "login_logo": "img/logo/logo.png",
    "login_logo_dark": "img/logo/logo-dark.png",  # Add a dark mode logo
    "welcome_sign": "Welcome to Agro Build Admin Portal",
    "copyright": "Agro Build Ltd.",
    
    # UI Customization
    "theme": "minty",
    "dark_mode_theme": "darkly",
    "show_ui_builder": True,  # Allow admin users to customize UI
    
    # Layout Options
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth",
        "agrobuild", 
        "agrobuild.Product", 
        "agrobuild.Order", 
        "agrobuild.UserProfile",
        "agrobuild.Blog"
    ],
    
    # Custom Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "agrobuild.Product": "fas fa-leaf",
        "agrobuild.Order": "fas fa-shopping-bag",
        "agrobuild.OrderItem": "fas fa-shopping-basket",
        "agrobuild.CartItem": "fas fa-cart-plus",
        "agrobuild.Category": "fas fa-tags",
        "agrobuild.UserProfile": "fas fa-user-circle",
        "agrobuild.Wishlist": "fas fa-heart",
        "agrobuild.Feedback": "fas fa-comment-alt",
        "agrobuild.Blog": "fas fa-newspaper",
        "agrobuild.BlogComment": "fas fa-comment-dots",
        "agrobuild.ContactMessage": "fas fa-envelope",
        "agrobuild.WateringReminder": "fas fa-tint",
        "agrobuild.NotificationHistory": "fas fa-bell",
    },
    
    # Custom Links
    "custom_links": {
        "agrobuild": [{
            "name": "Admin Dashboard",
            "url": "/admin/dashboard/",
            "icon": "fas fa-tachometer-alt",
            "permissions": ["auth.view_user"]
        }, {
            "name": "Visit Website",
            "url": "/",
            "icon": "fas fa-external-link-alt",
            "permissions": ["auth.view_user"]
    }, {
        "name": "Support",
        "url": "mailto:support@agrobuild.com",
        "icon": "fas fa-life-ring",
        "permissions": ["auth.view_user"]
    }, ]
    
    },
    
    # Advanced UI Features
    "related_modal_active": True,
    "custom_css": "css/admin-custom.css",  # Add custom CSS
    "custom_js": "js/admin-custom.js",     # Add custom JS
    "custom_css": "css/admin-table-style.css",
    "show_sidebar": True,
    "navigation_expanded": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "agrobuild.Product": "collapsible",
        "agrobuild.Order": "vertical_tabs"
    },
    "changeform_format_overrides": {
    "agrobuild.Product": "horizontal_tabs",
},
    # Search Models
    "search_model": ["agrobuild.Product", "agrobuild.Order", "auth.User"],
    
    # User Menu
    "usermenu_links": [
        {
            "name": "Support",
            "url": "mailto:support@agrobuild.com",
            "icon": "fas fa-life-ring",
            "new_window": True
        },
        {
            "model": "auth.user"
        }
    ],

}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "minty",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    },
    "actions_sticky_top": True
}